# Install required ODBC + compiler packages
[phases.setup]
aptPkgs = [
  "unixodbc",
  "unixodbc-dev",
  "msodbcsql18",
  "g++",
  "build-essential"
]

# No custom build command needed â€” pip install will work normally
