services:
  - type: web
    name: phidata-sql-bot
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    pythonVersion: 3.12.3
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SQL_SERVER
        sync: false
      - key: SQL_DATABASE
        sync: false
      - key: SQL_USERNAME
        sync: false
      - key: SQL_PASSWORD
        sync: false
